### ISSUE TITLE
"global" keys

### ISSUE THREAD

**Issue by Suya1671** [AckslD/nvim-whichkey-setup.lua#16]
How can I set keys that dont have a prefix? e.g `C-H` can link to something without me having to press anything before C-H

normally in vim you do `nnoremap <C-J> <C-W><C-J>`

**Comment by AckslD** [comment]
@Suyashtnt I would recommend you to use https://github.com/folke/which-key.nvim which is what I use nowadays as well :)

But anyway, why do you want to use whichkey for this? Seems like you just want to set that mapping which you can do normally as you wrote or the built-in lua api. I'd say whichkey is only useful for key sequences with more then one key since you can see the following options in the popup window.

**Comment by Suya1671** [comment]
> @Suyashtnt I would recommend you to use [folke/which-key.nvim](https://github.com/folke/which-key.nvim) which is what I use nowadays as well :)
> 
> But anyway, why do you want to use whichkey for this? Seems like you just want to set that mapping which you can do normally as you wrote or the built-in lua api. I'd say whichkey is only useful for key sequences with more then one key since you can see the following options in the popup window.

Ok, thanks for giving me a better plugin!
